name: Napi update

# Controls when the workflow will run
on:
  schedule:
    - cron: '20 20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest
            any::data.table
            any::ggplot2
            any::purrr
            any::progress

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run analysis
        run: Rscript -e 'source("temp.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add raw/raw*.rds
          git commit -m 'Raw data updated' || echo "No changes to commit"
          git add proc/prco*.rds
          git commit -m 'Processed data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
